@Worker_HostAddress = http://localhost:5000

POST {{Worker_HostAddress}}/File/set-path
Content-Type: application/json

{
  "Path": "C:\Users\Win10\Downloads\housing.csv"
}

###

GET {{Worker_HostAddress}}/DataPreview/columns
Accept: application/json

###

GET {{Worker_HostAddress}}/DataPreview/head
Accept: application/json

###

GET {{Worker_HostAddress}}/DataPreview/tail
Accept: application/json

###
